language: php

php:
  - '5.6'
  - '7.0'

cache:
  directories:
  - "$HOME/.composer"

before_script:
  - composer validate
  - composer install --no-interaction --dev -o --prefer-dist

script:
  - php -l src/
  - vendor/bin/phpcs --standard=psr2 --ignore=Tests src/
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
   - php vendor/bin/coveralls -v
