language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --dev -o

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src/
